refactor(eslint-remote-tester): convert to TS
AriPerkkio/eslint-remote-tester pull request #89
Opened 2021-04-25 16:46 UTC by MichaelDeBoey

2021-04-25 17:00 UTC, MichaelDeBoey commented
@AriPerkkio tests are fixed

2021-04-25 17:11 UTC, MichaelDeBoey commented
@AriPerkkio tests are fixed

2021-04-26 16:24 UTC, AriPerkkio requested changes
Thanks for the improvements @MichaelDeBoey. 

I initially setup the repositories package as plain Javascript due to its simplicity. But I do like having it as Typescript so this is welcome. 👍 
This however brings some complexity to other setups. Currently weekly scans ran under `./ci` are failing with error:
```
Error: Cannot find module '/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-remote-tester-repositories/dist/index.js'. Please verify that the package.json has a valid "main" entry
```
https://github.com/AriPerkkio/eslint-remote-tester/runs/2440214807?check_suite_focus=true

I believe before running those jobs the repositories package has to initialized and built. But I'm not sure what else is missing - I'm still running to that same error in local environment.

You should be able to run following in local environment once everything is setup properly:
```
cd ./ci
yarn log --config ./plugin-configs/eslint-core.config.js

./node_modules/.bin/eslint-remote-tester --config ./plugin-configs/eslint-core.config.js
```

2021-04-30 11:43 UTC, MichaelDeBoey commented
@AriPerkkio I've rebased onto `master` & updated all workflows

2021-04-30 14:39 UTC, AriPerkkio commented
CI jobs are now working OK. ✅

2021-04-30 15:24 UTC, AriPerkkio commented on repositories/scripts/filter-unique-repos.ts
> +    '../src/repositories.json',
```suggestion
    './src/repositories.json',
```

2021-04-30 15:24 UTC, AriPerkkio commented on repositories/package.json
> +        "directory": "repositories"
I had no idea such field exists, good catch! 💯

2021-04-30 15:26 UTC, AriPerkkio commented
https://github.com/AriPerkkio/eslint-remote-tester/blob/e6d5c47c2544f3395e5e437403e261b8f2bf767a/.github/workflows/ci.yml#L20-L22

Add `yarn build` for `./repositories` package here as well.
No idea how to add review comment on files which are not listed in changed. 😄

2021-04-30 15:27 UTC, MichaelDeBoey commented on repositories/src/index.ts
> +const shuffle = <T>(array: T[]): T[] =>
You can't make `functions` generic

2021-04-30 15:32 UTC, MichaelDeBoey commented on repositories/scripts/filter-unique-repos.ts
> +    '../src/repositories.json',
This path isn't correct

2021-04-30 15:36 UTC, MichaelDeBoey commented
@AriPerkkio Updated al things requested

2021-04-30 15:38 UTC, AriPerkkio commented on repositories/src/index.ts
> +const shuffle = <T>(array: T[]): T[] =>
Not sure what you mean. This is completely valid:

```ts
function shuffle<T>(array: T[]): T[] {
    return array
        .map(value => ({ value, order: Math.random() }))
        .sort((a, b) => a.order - b.order)
        .map(({ value }) => value);
}
```

2021-04-30 15:41 UTC, MichaelDeBoey commented on repositories/src/index.ts
> +const shuffle = <T>(array: T[]): T[] =>
I also like to have implicit returns, as that makes things shorter

2021-04-30 15:56 UTC, AriPerkkio commented on repositories/scripts/filter-unique-repos.ts
> +    '../src/repositories.json',
```
~/GIT/eslint-remote-tester/repositories$ yarn generate:repositories:unique
yarn run v1.22.5
$ ts-node ./scripts/filter-unique-repos.ts
Repositories 14496
Unique repositories 14496
Error: ENOENT: no such file or directory, open '../src/repositories.json'
```

2021-04-30 16:23 UTC, AriPerkkio approved these changes
Looks good, thanks for making the requested changes! 🎉

2021-04-30 16:24 UTC, merged

2021-12-26 05:13 UTC, G-Rath commented
@AriPerkkio since the codebase is now in TypeScript (so there are type definitions) would you be open to supporting `eslint-remote-tester.config.ts` using `ts-node` similar to how it's done in Webpack & Jest (among others)?

I'm happy to have a go at implementing if you are (I've done it in a few projects now - it's typically a pretty straightforward & small diff)